services:
  app:
    image: ghcr.io/modos189/ston-fi-swap-example:master
    ports:
      - "3000:3000"
    environment:
      - TON_CLIENT_API_KEY=""
      - MNEMONIC=""
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
